### ISSUE TITLE
[Enhancement 💡] Merge Metallurgy Advancement into Create Advancement for consistency with other Create mods. 

### ISSUE THREAD

**Issue by ffuentesm** [Lucreeper74/Create-Metallurgy#12]
I find it curious why Metallurgy has its own advancement tab when other create mods (Create Alloyed, Enchantment Industry, etc) have their mod progression into Create Advancement page. 

![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/e33f9156-0d11-4f6f-b1fe-fb27a735ac1a)
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/e4fb02e9-3316-4cf6-8c07-61f395342612)
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/42ebdaf2-cf9a-46af-b723-e7f1d42bf4dc)

I feel that the Metallurgic advancement tree could easily fit on the midpoint after acquiring the blaze burner. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/2f0b3972-9113-4faa-8de9-f10f1144c84d)

**Comment by Lucreeper74** [comment]
Hey @ffuentesm!
Yep, I had seen it but I forgot to think about it when I integrated the advancements. Let's say I did it the vanilla way without worrying about how Create did it. If its isn't that complex cause Create Enchantment Industry made a whole API to make Create more friendly to use for Addon developer and I don't want to use any API to just need to download Create Metallurgy and Create to play with it. So yea, that intresting new additions next update. Added to my todo list 👍
This will be close when I will added and commit it!
Thanks to be active by propose enhancement on Github, that help me to improve Create Metallurgy.

**Comment by ffuentesm** [comment]
no problem, I am enjoying this mod a lot, especially with how similar it is to TiC, and I plan to use both on my mod list.
So I want Metallurgic to be as friendly as possible with other mods from the get-go. 

Just like how I add both Create and Immersive Engineering to all my mod lists, even if I do not go deep into any of them. 
Just the ability to create a tool that integrates with other features seamlessly. If things work well. 
I will use Metallurgic as my go-to Ore processing mod. 

So I am waiting for the "ore integration" to use the Foundry to smelt all the ores. Like how people use Create for the Bulk Blasting.

**Comment by Lucreeper74** [comment]
> no problem, I am enjoying this mod a lot, especially with how similar it is to TiC, and I plan to use both on my mod list. So I want Metallurgic to be as friendly as possible with other mods from the get-go.
> 
> Just like how I add both Create and Immersive Engineering to all my mod lists, even if I do not go deep into any of them. Just the ability to create a tool that integrates with other features seamlessly. If things work well. I will use Metallurgic as my go-to Ore processing mod.
> 
> So I am waiting for the "ore integration" to use the Foundry to smelt all the ores. Like how people use Create for the Bulk Blasting.

That what I will aiming for the Futur of Create Metallurgy, you can check and debate on Discord in the Suggestion forum there is a pinned post that made for that [here](https://discord.com/channels/996022627430846464/1250531058714411038). Cause at the beginning, I was a bit lost on which direction to take.

**Comment by Lucreeper74** [comment]
Hey @ffuentesm!
I've got news! I know how to implement integrated Advancements to Create ones. I will add it when I go back to development.

**Comment by Lucreeper74** [comment]
Hey @ffuentesm :wave:
This is done in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/46560e333046bd7f1f26c39410e9923d2c219254), I was busy with other issues and optimizations with my mod which took some time. But it is done, and will be available in the next update.
