### ISSUE TITLE
[Enhancement 💡] Input from top

### ISSUE THREAD

**Issue by Elnhomantia** [Lucreeper74/Create-Metallurgy#18]
Please let us input items from the top of the foundry lid. Also, please don't make the glass lid only work for alloying and vis-versa.

**Comment by Lucreeper74** [comment]
Hello 👋 @Elnhomantia 
This is planned no worries. Create Metallurgy is recent, a lot of thing are not ergonomic and useful for now. I just need to take the time to think about the way I will make the Foundry more useful and practical.
But thanks to take the time to propose your suggestions.

**Comment by Elnhomantia** [comment]
I also have another sugestion, with the bassin you added, maybe doing like the create tank, making a sort of multiblock with a max size of 3\*3*3, would bo cool

**Comment by Lucreeper74** [comment]
Of course, this is planned no worries, take a look at Mod page planned features list.

**Comment by Lucreeper74** [comment]
Hey @Elnhomantia 👋 
I have added your suggestion to Create Metallurgy in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/f4c583aa863ea464045b1d4f2d61548a5b797443)
