### ISSUE TITLE
Create Spout above Casting Basin will not work

### ISSUE THREAD

**Issue by Qi-Month** [Lucreeper74/Create-Metallurgy#20]
But using fluid hopper or pipe to enter the Casting Basin will work normally.

Mod Version: 0.0.5
Forge Version: 47.2.30
Game Version: 1.20.1
![image](https://github.com/user-attachments/assets/96042c7e-26a4-4310-b0d6-e5f8ab0a8345)
![image](https://github.com/user-attachments/assets/a6eb0187-02a0-49be-9cd8-e8b5319e2ec4)

**Comment by Lucreeper74** [comment]
Hey @Qi-Month 👋
Thanks to create an issue here for what we have talk about on Discord 👍

**Comment by Lucreeper74** [comment]
Hello @Qi-Month 👋 
I found the bug, that was just a stupid forget, my bad. That is fixed here [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/19beae94363c315c8e72ab4b6f6b30befba86f50)
