### ISSUE TITLE
[Enhancement 💡/ Question] 1.20.1+ Casting Table Capacity

### ISSUE THREAD

**Issue by accessdenied0** [Lucreeper74/Create-Metallurgy#23]
**Is your feature request related to a problem? Please describe.**
I found that the casting table only can hold 90mb, but I had a few custom recipes, with a custom mold, which would need more than 90, but 1000mb (1Bucket) as amount. 

**Describe the solution you'd like**
I would love that the table, if that is possible a bigger max fluid capacity. It could be, if possible, dynamic, that it checks the recipe, similar to TiC's Table.

**Additional context**
I did read the issue about the Casting Basin and I get where this amount is coming from (- which is strange at it self, because it was always 144 per ingot), but it makes other kinds of recipes not possible... which would be really ideally, since this mod is basically, in most ways, exactly what I have been looking for.

**Comment by Lucreeper74** [comment]
Hey @accessdenied0 👋 
I know your disappointment, a few people give me the same feedback. No worries, I heard you! This is already adjusted (Waiting to finish smth else to push it to Github). Casting Basin/Table will have a dynamic fluid capacity determined by the fluid requirement set in the json file. This will be available in the next update.

Also, for the ingot value of fluid, I made this cause TiC use 90mB for an ingot. So, I use the same amount to have more compatibility and avoid duplication issues. I don't know what mod use 144mB of fluid for ingot, cause for an block it would be 1 296mB.

_When the Github commit in question is pushed, I will close this post._

Thanks taking the time to propose your suggestion! 👍 
If you want more informations or ask help, you can join Create Metallurgy Discord [here](https://discord.com/invite/KGQr5a2qc9)

**Comment by Lucreeper74** [comment]
Hey @accessdenied0 👋 
Sorry for being late, see on Create Metallurgy Discord why the development is so slow. But I have finally push the code for the rework of Casting Basin/Table with the dynamic fluid capacity depending on the recipe requierement. You can found the main commit here that adding the feature -> [Github Commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/3a674ff32bc3435c76b8fd98884cb8174546fa91)
