### ISSUE TITLE
[BUG 🐜]casting table causes the fluid to disappear

### ISSUE THREAD

**Issue by SSWTLZZ** [Lucreeper74/Create-Metallurgy#26]
**Describe the bug**
Casting table causes the fluid to disappear.

**To Reproduce**
1.Melt the metal in a casting basin
2.Place a casting table underneath the casting basin to hold the molten metal
3.The molten metal disappear
**Expected behavior**
When casting table is placed

**Screenshots**
![image](https://github.com/user-attachments/assets/6e08970e-78b9-4996-b4fd-8d58af176a3b)

**Environment:**
 - MC/Forge version 1.20.1
 - Create version 0.5.1h
 - Create Metallurgy version 0.0.5
- Others mods / modpacks, datapacks

**Additional context**
I've found that after the fluid disappears, then putting a item drain underneath it and then switching the opening of the basin, the fluid will appear in the item drain.
I'm using machine translation so it may not be accurate. Sorry.

**Comment by Lucreeper74** [comment]
Hey @SSWTLZZ 👋 
Firstly, thanks taking the time to translate and make write your post. That really help me to find bugs and improve Create Metallurgy 👍

So, its not a "bug" that just a weird behavior of Create code (Cause Foundry Basin work partially with the Create Basin code).
There is just an secret fluid tank that handle the recipe output until it can release it into an external fluid tank. However, this happen cause the Casting table in v0.0.5 has only 90mb of fluid, and if the recipe output is higher the secret fluid tank keep the fluid until you put Item Drain which have 1500mb of capacity.
No worries, the Foundry Basin spoutput behavior has been overhaul and will be changed in the next update. In addition, the Casting Table capacity will be dynamic depending on the recipe requirement (basically like TiC).

If you want further explanation if you don't understand correctly what I'm saying. You can ask me on Create Metallurgy Discord [here](https://discord.gg/KGQr5a2qc9)
