### ISSUE TITLE
[Enhancement 💡] Compat for other modded metals

### ISSUE THREAD

**Issue by Command17** [Lucreeper74/Create-Metallurgy#30]
**Is your feature request related to a problem? Please describe.**

This feature request is not related to a problem (I think), but this feature would be very nice for large modpacks with this mod (with, for example the _Thermal Series_).

**Describe the solution you'd like**

Molten metal and dust versions for uranium, lead, tin, nickel, silver, osmium, platinum, quicksilver (since those have crushed versions in _Create_).

**Describe alternatives you've considered**

_Create: Molten Metals_ does have molten version of those metals, but from what I've read it's just melting them down, not refining them.

**Additional context**

--

Thanks

**Comment by Lucreeper74** [comment]
Hey @Command17 👋 
No worries that what I'm working on currently! Already some metals are already pushed to github 1.19.2 branch here [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/9e5d94feeb8a0ae5137ee35d502793d457c0baa2)
Also, you can join Create Metallurgy Discord and subscribe to the Sneak Peaks channel, to find a list of minerals that I will add, and it will evolve in the future!

However thanks taking the time to share your enhancement! That really engage me to continue!
