### ISSUE TITLE
[Enhancement 💡] Compat with Create Heat JS mod pls

### ISSUE THREAD

**Issue by liuseniubi** [Lucreeper74/Create-Metallurgy#31]
Could u make ur wonderful mod compat with the [Create Heat JS Mod](https://www.curseforge.com/minecraft/mc-mods/create-heat-js)（A mod that can make ur own heat block such as working Furnace or sth）

**Comment by Lucreeper74** [comment]
Hey @liuseniubi 👋

I think this is already possible! Someone on Create Metallurgy [Discord](https://discord.gg/KGQr5a2qc9) have post a screen with a custom heat block using Create Heat JS mod. You can just ask him how he does it maybe.
But I will see if i have anything to do in my mod to make a proper compatibility.

Thanks you taking the time to share your enhancement! That really engage me keep it up!

**Comment by liuseniubi** [comment]
> Hey @liuseniubi 👋
> 
> I think this is already possible! Someone on Create Metallurgy [Discord](https://discord.gg/KGQr5a2qc9) have post a screen with a custom heat block using Create Heat JS mod. You can just ask him how he does it maybe. But I will see if i have anything to do in my mod to make a proper compatibility.
> 
> Thanks you taking the time to share your enhancement! That really engage me keep it up!

Thanks for reply! I just tried Lava for custom heat, but it seems not working on every fluid, and maybe a Create Heat JS problem, sorry for the issue, and A BIG THANK for your mod! ^^
