### ISSUE TITLE
[BUG 🐜]fluid in casting table or casting basin disappear

### ISSUE THREAD

**Issue by SSWTLZZ** [Lucreeper74/Create-Metallurgy#35]
**Describe the bug**
Fluid in the casting table or casting basin disappears while processing; I suspect this is caused by unloading the chunk.

**To Reproduce**
1. Fill the table or basin with molten metal.
2. Quit the game or teleport somewhere to unload the chunk.
3. The fluid disappears.

**Expected behavior**
The fluid should not disappear.

**Screenshots**

**Environment:**
 - MC/Forge version 47.3.10
 - Create version 0.5.1.i
 - Create Metallurgy version 0.0.6
- Others mods / modpacks, datapacks

**Additional context**

**Comment by Lucreeper74** [comment]
Hey @SSWTLZZ !
Seems weird to me. I have implemented something to save it when the chunk is unload. There must be a specific case that I haven't anticipated.
Thanks you taking the time to open this issue, this really help me! I will dig it. I leave this post open until its fixed!

**Comment by Lucreeper74** [comment]
Hello again @SSWTLZZ !
This has been fixed in this commit! [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/ea9970b0c5d19dda7eb9518688b9761d072a0e27)

It will no longer cause this bug normally
