### ISSUE TITLE
[BUG 🐜] More fluid inputs/outputs than supported log spam

### ISSUE THREAD

**Issue by TheLMiffy1111** [Lucreeper74/Create-Metallurgy#36]
**Describe the bug**
When loading the game, the console is spammed with patterns of the following:
`Your custom createmetallurgy:melting recipe has more fluid outputs (1) than supported (0).`
`Your custom createmetallurgy:alloying recipe has more fluid inputs (2) than supported (0).`
`Your custom createmetallurgy:alloying recipe has more fluid outputs (1) than supported (0).`
This is caused by melting/alloying recipes not having fluid input/output counts set.

**Expected behavior**
Melting recipes should support at least 1 fluid output.
Alloying recipes should support 2 fluid inputs and at least 1 fluid output.

**Environment:**
 - MC/Forge 1.19.2
 - Create version 0.5.1.i
 - Create Metallurgy version 0.0.6

**Additional context**
Melting/alloying recipes probably should not be supporting 2 item outputs.

**Comment by Lucreeper74** [comment]
Hey @TheLMiffy1111 👋 

I thought that was only in my Programming environment, but it doesn't seem to. I will fix it when I have the time.
I will keep this thread open until it's fixed.
Thanks for taking the time to report this 👍

**Comment by Lucreeper74** [comment]
Hello back @TheLMiffy1111 👋 
Its has been fixed here [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/e0e26935743af72c89d42f98a76f69b8e081717a).
I just forgot to specify the recipe limits.

**Comment by Garagoth** [comment]
Is this fix required in 1.20.1 branch as well?
It wasn't merged from 1.19 to 1.20 branch.

**Comment by Lucreeper74** [comment]
> Is this fix required in 1.20.1 branch as well? It wasn't merged from 1.19 to 1.20 branch.

No worries, I first add the commit to the main branch, and before the release, I merge all the main to the remains branches.
