### ISSUE TITLE
[BUG 🐜]StartUp Crash 1.19.2

### ISSUE THREAD

**Issue by f0kx** [Lucreeper74/Create-Metallurgy#4]
**Describe the bug**

**To Reproduce**
1. Upload Mod to Server
2. Start Server
3. Crash
4. Crashlog

**Environment:**
 - Forge 43.3.8
 - Create version : 0.5.1.f
 - Create Metallurgy version : 0.0.2
Own Modpack

[crash-2024-06-02_23.21.07-fml.txt](https://github.com/user-attachments/files/15526927/crash-2024-06-02_23.21.07-fml.txt)

**Comment by Lucreeper74** [comment]
Hey! Its already a know issue. It has been fixed in this [Commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/edca9b00de826b6fa0dd1ccedc81245b1eeee324)

Thanks for helping Create Metallurgy developpement with your issue report!
