### ISSUE TITLE
[BUG 🐜]Molten fluid can not destroy item

### ISSUE THREAD

**Issue by SSWTLZZ69** [Lucreeper74/Create-Metallurgy#42]
**Describe the bug**
just like the title

**To Reproduce**
Pour molten fluid into the world
Throw an item into the molten fluid
The item remains intact and is not destroyed

**Expected behavior**
The item should be destroyed when it comes into contact with molten fluid

**Screenshots**

**Environment:**
 - MC/Forge version 47.3.10
 - Create version 0.5.1j
 - Create Metallurgy version 0.0.6
- Others mods / modpacks, datapacks

**Additional context**
I'm not sure if this is an intended feature or a bug

**Comment by Lucreeper74** [comment]
Hey @SSWTLZZ69 !

Thanks taking the time to report bugs! This is indeed an oversight, I didn't really understand the custom liquid integrations on Forge. Special thanks to Jason for the [fix ](https://github.com/Lucreeper74/Create-Metallurgy/pull/43/files#diff-93b5c39bfc486ad41112a80268bd827dbc812dc0e69f6cca4ccd3f07809b462a) and adding a lava sound to this!
