### ISSUE TITLE
KubeJS Plugin Support

### ISSUE THREAD

**Issue by Qi-Month** [Lucreeper74/Create-Metallurgy#6]
**KubeJS Plugin Support**
I think this Mod is very suitable for making Modpack, but since KubeJS is not supported, I often have to use the combination of custom and forEach to write Recipes, which I think is very inconvenient.
If you can I really recommend adding KubeJS Recipes support
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/115912382/5aec64d1-47fd-4886-828f-f987331da2dc)

**Comment by Lucreeper74** [comment]
Hey!
It's planned, no worries. I just need to learn how to do it, I already use KubeJS but never looked at how to make a mod compatible with it.
I'm fixing some bugs first and will do it after that.

**Comment by Qi-Month** [comment]
> 嘿！这是计划好的，不用担心。我只需要学习如何去做，我已经使用 KubeJS，但从未研究过如何使 mod 与它兼容。我首先修复了一些错误，之后会这样做。

Oh! Thank you so much!

**Comment by Qi-Month** [comment]
Oh! Thank you so much!

**Comment by Qi-Month** [comment]
Looking forward to your new version!
By the way, I am 1.20.1

**Comment by Lucreeper74** [comment]
Hi @Qi-Month again!
After looking deeper in how KubeJS work, if I have understood your suggestion correctly, create functions like KubeJS-Create-Addon adds, I will need to make an entire new mod especially for the integration of Create Metallurgy with KubeJS if i want to keep Create Metallurgy playable without using KubeJS all time & to be organized.
Which is not really possible for me cause Create Metallurgy taking me already a lot of time in addition to my private life.
Sorry for your disappointment, you will just use KubeJS custom recipes like in Datapacks.
